### ISSUE TITLE
Composite Resource at component level for each workload

### ISSUE THREAD

**Issue by subhashvinjamuri** [ykuijs/M365DSC.CRG#16]
Hi,
Pretty impressed with New-compositeResource function to generate composite resource at Workload level (ie Teams, EXO, SPO etc). Is there any other function/module that handles this at Component level as well within a Workload ? We want to main the configuration for each workload and devide them to component level, but as modules. So, as example, if I give input filter as $workload = 'Teams', expecting this to generate respective .psm1 and .psd1 files for each component inside Teams workload ie generate TeamsAppPermissionPolicy\TeamsAppPermissionpolicy.psd1 & \temsApppermisionPOlicy.psm1. file structure. Any inputs on this ? want to use this for our pipeline.

**Comment by subhashvinjamuri** [comment]
@ykuijs Do you have some inputs here by chance ?

**Comment by ykuijs** [comment]
Hi @subhashvinjamuri,

Thanks for the feedback. Good to hear you are liking the work I have been doing.

This module has been created for the new version [Microsoft365DSC/Azure DevOps whitepaper](https://aka.ms/M365DSCWhitepaper) (to be released shortly). In that whitepaper, we have chosen the workload approach.

To change the code to allow the creation of a resource per component will be a big change, which currently I do not have any time for. Of course, you could update the code yourself and submit a PR.

**Comment by subhashvinjamuri** [comment]
Thanks @ykuijs . I think I was able to modify the function to generate composite resources at component level. But to test it, i have question on using this composite resource.
From the above devops example, the input file is- 'production.psd1' actually contains the data , Because of that, we need to give all component's data in that file at top level (ex: Teasmeetingpolicy hash table, teamsapppermisiionPOlicy etc).  I am thinking if I want to give some data in ..\M365Config\0.0.1\DscResources\Teams\Teams.psd1 . And call that configuration from M365configuration.ps1 script, so it loops through al components and generate final 'Teams' configuration. Any suggestions to achieve this ?

**Comment by ykuijs** [comment]
In the DevOps example we are using the default feature of DSC to split Configurations and Configuration Data:
- https://learn.microsoft.com/en-us/powershell/dsc/configurations/configdata?view=dsc-1.1
- https://learn.microsoft.com/en-us/powershell/dsc/configurations/separatingenvdata?view=dsc-1.1

The method you are describing embeds the configuration data into the module, which means updating data by M365 admins will become much more difficult. So I would not go down that road. I would stick to the native option of inserting config data
